apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-dms-rp-kv-0
  namespace: ns1
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "dms-rp-kv-0"
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret                                      
        - |
          objectName: secret2
          objectType: secret
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47" 